elevenlabs:
  api_key: ""
  voice_id: "JBFqnCBsd6RMkjVDRZzb"  # George
  model_id: "eleven_multilingual_v2"
  voice_settings:
    stability: 0.5
    similarity_boost: 0.75
    style: 0.4

clips_dir: "clips"

platforms:
  - youtube_shorts
  - tiktok
  - instagram_reels

assembly:
  clip_selection: "sequential"  # sequential | random | round_robin
  font: "/System/Library/Fonts/Helvetica.ttc"
  font_size: 48
  font_color: "white"
  border_width: 2
  border_color: "black"
  text_y_position: "h-th-120"  # FFmpeg expression
  max_chars_per_line: 30
  resolution: "1080x1920"
  fps: 30
